ECommerce.WebApp/Models/Configurations/Footer/ManageFooterViewModel.cs
using ECommerce.Application.Services.Configurations.Dtos;
using ECommerce.Application.Services.Configurations.Dtos.Footer;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.WebApp.Models.Configurations.Footer
{
    public class ManageFooterViewModel
    {
        public List<BlogModel> listBlog { get; set; }
        public List<SocialModel> listSocial { get; set; }
        public ConfigurationModel config { get; set; }
    }
}

ECommerce.WebApp/Controllers/Admin/ManageConfigurationController.cs
using ECommerce.Application.Services.Bank;
using ECommerce.Application.Services.Configurations;
using ECommerce.WebApp.Models.Configurations.Footer;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ECommerce.WebApp.Controllers.Admin
{
    public class ManageConfigurationController : Controller
    {
        private IFooterService _footerService;
        private IConfigurationService _configurationService;
        private IBankService _bankService;
        public ManageConfigurationController(IFooterService footerService, IConfigurationService configurationService, IBankService bankService)
        {
            _footerService = footerService;
            _configurationService = configurationService;
            _bankService = bankService;
        }
        public async Task<IActionResult> ManageFooter()
        {
            var blogs = await _footerService.getAllBlog();
            var socials = await _footerService.getAllSocial();
            var configs = await _configurationService.getConfiguration();

            var model = new ManageFooterViewModel()
            {
                listBlog = blogs,
                listSocial = socials,
                config = configs
            };
            return View(model);
        }
        public async Task<IActionResult> AddBlog()
        {
            return View();
        }
        public async Task<IActionResult> BlogDetail(int BlogId)
        {
            var blog = await _footerService.getBlogDetail(BlogId);
            return View(blog);
        }

        public async Task<IActionResult> ManageBank()
        {
            var listBank = await _bankService.getListBank();
            return View(listBank);
        }
    } 
}

ECommerce.WebApp/Views/ManageConfiguration/AddBlog.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="https://cdn.tiny.cloud/1/4ctr9pi6o8mlflu8si6gdszgl62tn4zl73knhf3tkqalszsx/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Thêm Blog</h6>
    </div>
    <div class="card-body">
        <div class="form-group mb-2">
            <label class="mr-2">Cột</label>
            <select class="form-control blog-position">
                @for (int i = 1; i <= 2; i++)
                {
                    <option value="@i">@i</option>
                }
            </select>
        </div>

        <div class="form-group mb-2">
            <label class="mr-2">Tiêu đề</label>
            <input class="form-control blog-title" value="">
        </div>

        <div class="form-group mb-2">
            <label>Nội dung</label>
            <textarea id="blog-content"></textarea>
        </div>

        <div class="text-center mt-4">
            <button class="btn-primary btn add-blog">Thêm</button>
        </div>
    </div>
</div>
<script>
    $('.add-blog').click(function () {
        var request = {
            BlogTitle: $('.blog-title').val(),
            BlogContent: tinymce.get("blog-content").getContent(),
            BlogPosition: $('.blog-position').val()
        };
        apiAddBlog(request);
    })
    function apiAddBlog(request) {
        $.ajax({
            url: '/api/ManageConfigurationsAPI/AddBlog',
            data: JSON.stringify(request),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            success: function (data) {
                window.location.href = "/ManageConfiguration/ManageFooter";
            },
            error: function (data) {
                console.log(data);
                alert(data.responseJSON.message)
            }
        });
    }
</script>

<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'a11ychecker advcode casechange export formatpainter image editimage linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tableofcontents tinycomments tinymcespellchecker',
        toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter image editimage pageembed permanentpen table tableofcontents',
        toolbar_mode: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
    });
</script>

ECommerce.WebApp/Views/ManageConfiguration/BlogDetail.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<script src="https://cdn.tiny.cloud/1/4ctr9pi6o8mlflu8si6gdszgl62tn4zl73knhf3tkqalszsx/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Chi tiết Blog</h6>
    </div>
    <div class="card-body">
        <div class="form-group mb-2">
            <label class="mr-2">Cột</label>
            <select class="form-control blog-position">
                @for (int i = 1; i <= 2; i++)
                {
                    if (Model.BlogPosition == i)
                    {
                        <option value="@Model.BlogPosition" selected>@Model.BlogPosition</option>
                    }
                    else
                    {
                        <option value="@i">@i</option>
                    }
                }
            </select>
        </div>

        <div class="form-group mb-2">
            <label class="mr-2">Tiêu đề</label>
            <input class="form-control blog-title" value="@Model.BlogTitle">
        </div>

        <div class="form-group mb-2">
            <label>Nội dung</label>
            <textarea id="blog-content">@Model.BlogContent</textarea>
        </div>

        <div class="text-center mt-4 d-flex">
            <button class="btn-primary btn update-blog mr-2">Cập nhật</button>
            <button class="btn-danger btn delete-blog">Xóa</button>
        </div>
    </div>
</div>
<script>
    $('.delete-blog').click(function () {
        if (confirm("Xác nhận xóa") == true) {
            apiDeleteBlog(@Model.BlogId);
        }
    })
    $('.update-blog').click(function () {
        var request = {
            BlogId: @Model.BlogId,
            BlogTitle: $('.blog-title').val(),
            BlogContent: tinymce.get("blog-content").getContent(),
            BlogPosition: $('.blog-position').val()
        };
        apiUpdateBlog(request);
    })
    function apiDeleteBlog(BlogId) {
        $.ajax({
            url: '/api/ManageConfigurationsAPI/DeleteBlog',
            data: JSON.stringify(BlogId),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            success: function (data) {
                alert(data.message);
                window.location.href = "/ManageConfiguration/ManageFooter"
            },
            error: function (data) {
                console.log(data);
                alert(data.responseJSON.message)
            }
        });
    }
    function apiUpdateBlog(request) {
        $.ajax({
            url: '/api/ManageConfigurationsAPI/UpdateBlog',
            data: JSON.stringify(request),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            success: function (data) {
                alert(data.message);
            },
            error: function (data) {
                console.log(data);
                alert(data.message)
            }
        });
    }
</script>

<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'a11ychecker advcode casechange export formatpainter image editimage linkchecker autolink lists checklist media mediaembed pageembed permanentpen powerpaste table advtable tableofcontents tinycomments tinymcespellchecker',
        toolbar: 'a11ycheck addcomment showcomments casechange checklist code export formatpainter image editimage pageembed permanentpen table tableofcontents',
        toolbar_mode: 'floating',
        tinycomments_mode: 'embedded',
        tinycomments_author: 'Author name',
    });
</script>

ECommerce.WebApp/Views/ManageConfiguration/ManageBank.cshtml
@using Microsoft.Extensions.Configuration
@inject IConfiguration Configuration
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary text-center">Thông tin chi tiết</h6>
    </div>
    <div class="card-body p-2">
        <div class="mx-auto mb-4">
            <div class="row">
                <div class="col-sm-6 mb-4">
                    <div class="text-left mb-2 text-primary"><strong>Thông tin cơ bản</strong></div>
                    <input class="bank-id" value="" disabled hidden/>
                    <div class="form-group mb-4">
                        <label>Tên</label>
                        <input type="text" class="form-control bank-accountname" value="">
                    </div>
                    <div class="form-group mb-4">
                        <label>Ngân hàng</label>
                        <input type="text" class="form-control bank-name" value="">
                    </div>
                    <div class="form-group mb-4">
                        <label>Số tài khoản</label>
                        <input type="text" class="form-control bank-accountnumber" value="">
                    </div>
                </div>
                <div class="col-sm-6 mb-4">
                    <div class="form-group mb-4">
                        <label>Ảnh ngân hàng</label>
                        <div class="d-flex flex-wrap">
                            <div class="">
                                <div class="border" style="height: 100px; width: 100px;">
                                    <label class="mb-0 w-100 h-100 d-none align-items-center justify-content-center"
                                           for="pic-size" style="cursor: pointer">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="24"
                                             height="24" viewBox="0 0 24 24" fill="none"
                                             stroke="#ddd" stroke-width="1" stroke-linecap="round"
                                             stroke-linejoin="round"
                                             class="feather feather-plus-circle">
                                            <circle cx="12" cy="12" r="10"></circle>
                                            <line x1="12" y1="8" x2="12" y2="16"></line>
                                            <line x1="8" y1="12" x2="16" y2="12"></line>
                                        </svg>
                                    </label>
                                    <input type="file" class="form-control-file image-uploaded"
                                           id="pic-size" hidden>
                                    <div class="image-wrapper w-100 h-100 position-relative d-flex align-items-center justify-content-center p-1">
                                        <img class="mw-100 mh-100"
                                             src="../assets/images/bidv.png" alt="">
                                        <span class="position-absolute remove-upload"
                                              style="right: 0; top: 0; cursor: pointer;">
                                            <svg xmlns="http://www.w3.org/2000/svg" width="18"
                                                 height="18" viewBox="0 0 24 24" fill="none"
                                                 stroke="red" stroke-width="1" stroke-linecap="round"
                                                 stroke-linejoin="round" class="feather feather-x">
                                                <line x1="18" y1="6" x2="6" y2="18"></line>
                                                <line x1="6" y1="6" x2="18" y2="18"></line>
                                            </svg>
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <button id="confirm-change" class="btn btn-primary">Lưu</button>
            </div>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered order-table" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th scope="col">Ảnh</th>
                        <th scope="col">Tên ngân hàng</th>
                        <th scope="col">Tên</th>
                        <th scope="col">Số tài khoản</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody class="bank-list">
                    @foreach (var item in Model)
                    {
                        <tr id="bank-@item.BankId">
                            <td>
                                <div class="d-flex align-items-center justify-content-center border p-1 mr-2" style="height: 120px; width: 120px;">
                                    <img class="mw-100 mh-100" src="@Configuration["ImagePath:Bank"]@item.BankImage" alt="">
                                </div>
                            </td>
                            <td>@item.BankName</td>
                            <td>@item.BankAccountName</td>
                            <td>@item.BankAccountNumber</td>
                            <td>
                                <button class="btn btn-primary">Chỉnh sửa</button>
                                <button class="btn btn-danger" onclick="deleteBank(@item.BankId)">Xóa</button>
                            </td>
                        </tr>
                    }

                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $('#confirm-change').click(function () {
        console.log($('.bank-id').val())
        if ($('.bank-id').val() === '') {
            addBank()
        } else {
            updateBank()
        }
    })

    function addBank() {
        var request = {
            BankName: $('.bank-name').val(),
            BankAccountNumber: $('.bank-accountnumber').val(),
            BankAccountName: $('.bank-accountname').val(),
        };
        apiAddBank(request);
    }
    function updateBank() {
        var request = {
            BankId: $('.bank-id').val(),
            BankName: $('.bank-name').val(),
            BankAccountNumber: $('.bank-accountnumber').val(),
            BankAccountName: $('.bank-accountname').val(),
        };
        apiUpdateBank(request);
    }
    function deleteBank(bankId) {
        apiDeleteBank(bankId);
    }

    function apiAddBank(request) {
        $.ajax({
            url: '/api/ManageConfigurationsAPI/AddBank',
            data: JSON.stringify(request),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            success: function (data) {
                console.log(data);
                alert(data.message);
                renderHtmlAddBank(data.objData, request);
            },
            error: function (data) {
                console.log(data);
                alert(data.message);
            }
        });
    }
    function apiDeleteBank(bankId) {
        $.ajax({
            url: '/api/ManageConfigurationsAPI/DeleteBank',
            data: JSON.stringify(bankId),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            success: function (data) {
                alert(data.message);
                $(`#bank-${bankId}`).empty();
            },
            error: function (data) {
                alert(data);
            }
        });
    }
    function apiUpdateBank(request) {
        $.ajax({
            url: '/api/ManageConfigurationsAPI/UpdateBank',
            data: JSON.stringify(request),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            success: function (data) {
                console.log(data);
                alert(data.message);
            },
            error: function (data) {
                console.log(data);
                alert(data);
            }
        });
    }

    function renderHtmlAddBank(id, bank) {
        $('.bank-list').append(htmlBank(id, bank));
    }
    function renderHtmlUpdateBank(request) {
        $('.bank-list').append(htmlBank(request.bankId, request));
    }
    function htmlBank(id, bank) {
        var html = `
            <tr id="bank-${id}">
                <td>
                    <div class="d-flex align-items-center justify-content-center border p-1 mr-2" style="height: 120px; width: 120px;">
                        <img class="mw-100 mh-100" src="@Configuration["ImagePath:Bank"]${bank.BankImage}" alt="">
                    </div>
                </td>
                <td>${bank.BankName}</td>
                <td>${bank.BankAccountName}</td>
                <td>${bank.BankAccountNumber}</td>
                <td>
                    <button class="btn btn-primary">Chỉnh sửa</button>
                    <button class="btn btn-danger" onclick="deleteBank(${id})">Xóa</button>
                </td>
            </tr>
        `;
        return html;
    }
</script>

ECommerce.WebApp/Views/ManageConfiguration/ManageFooter.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Quản lý Blog</h6>
        <a class="btn btn-success" href="@Url.Action("AddBlog","ManageConfiguration")">Thêm blog</a>
    </div>
    <div class="card-body">
        <div class="font-weight-bold mb-2">Công ty</div>
        <div class="table-responsive">
            <table class="table table-bordered order-table" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Cột</th>
                        <th>Tên Blog</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @for(int i = 0; i < Model.listBlog.Count; i++)
                    {
                        if (Model.listBlog[i].BlogPosition == 1)
                        {
                            <tr>
                                <td>@Model.listBlog[i].BlogPosition</td>
                                <td>@Model.listBlog[i].BlogTitle</td>
                                <td class="text-center">
                                    <a href="@Url.Action("BlogDetail", "ManageConfiguration", new { BlogId = Model.listBlog[i].BlogId})" style="color: var(--blue-dior);">Chi tiết</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

        <div class="font-weight-bold mb-2">Chính sách hỗ trợ</div>
        <div class="table-responsive">
            <table class="table table-bordered order-table" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Cột</th>
                        <th>Tên Blog</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @for(int i = 0; i < Model.listBlog.Count; i++)
                    {
                        if (Model.listBlog[i].BlogPosition == 2)
                        {
                            <tr>
                                <td>@Model.listBlog[i].BlogPosition</td>
                                <td>@Model.listBlog[i].BlogTitle</td>
                                <td class="text-center">
                                    <a href="@Url.Action("BlogDetail", "ManageConfiguration", new { BlogId = Model.listBlog[i].BlogId})" style="color: var(--blue-dior);">Chi tiết</a>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

        <div class="font-weight-bold mb-2">Mạng xã hội</div>
        <div class="table-responsive">
            <table class="table table-bordered order-table" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Cột</th>
                        <th>Icon</th>
                        <th>Mạng xã hội</th>
                        <th>Đường dẫn</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.listSocial)
                    {
                        if (item.Position == 1)
                        {
                            <tr>
                                <td>@item.Position</td>
                                <td>
                                    <input class="social_icon-@item.SocialId form-control" placeholder="Link" value="@item.Icon">
                                </td>
                                <td>
                                    <input class="social_name-@item.SocialId form-control" placeholder="Link" value="@item.SocialName">
                                </td>
                                <td>
                                    <input class="social_url-@item.SocialId form-control" placeholder="Link" value="@item.SocialUrl">
                                </td>
                                <td class="text-center">
                                    <button class="btn btn-primary" onclick="updateSocial(@item.SocialId)">Cập nhật</button>
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>

        <div class="font-weight-bold mb-2">Thông tin liên hệ</div>
        <div>
            <div class="table-responsive">
                <table class="table table-bordered order-table" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Cột</th>
                            <th>Icon</th>
                            <th>Tiêu đề</th>
                            <th>Nội dung</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.listSocial)
                        {
                            if (item.Position == 2)
                            {
                                <tr>
                                    <td>@item.Position</td>
                                    <td>
                                        <input class="social_icon-@item.SocialId form-control" placeholder="Link" value="@item.Icon">
                                    </td>
                                    <td>
                                        <input class="social_name-@item.SocialId form-control" placeholder="Link" value="@item.SocialName">
                                    </td>
                                    <td>
                                        <input class="social_url-@item.SocialId form-control" placeholder="Link" value="@item.SocialUrl">
                                    </td>
                                    <td class="text-center">
                                        <button class="btn btn-primary" onclick="updateSocial(@item.SocialId)">Cập nhật</button>
                                    </td>
                                </tr>
                            }
                        }
                        <tr>
                            <td>2</td>
                            <td></td>
                            <td>Địa chỉ</td>
                            <td>
                                <div class="d-flex">
                                    <input class="form-control mr-2 config-address" placeholder="Địa chỉ" value="@Model.config.Address">
                                    <input class="form-control config-addressurl" placeholder="Đường dẫn" value="@Model.config.AddressUrl">
                                </div>
                            </td>
                            <td class="text-center">
                                <button class="btn btn-primary" onclick="updateAddress()">Cập nhật</button>
                            </td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td></td>
                            <td>Thời gian làm việc</td>
                            <td>
                                <div class="d-flex">
                                    <input class="form-control mr-2 config-starttime" value="@Model.config.StartTime" type="time">
                                    <input class="form-control config-endtime" value="@Model.config.EndTime" type="time">
                                </div>
                            </td>
                            <td class="text-center">
                                <button class="btn btn-primary" onclick="updateTime()">Cập nhật</button>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
    function updateSocial(id){
        var request = {
            SocialId: id,
            Icon: $(`.social_icon-${id}`).val(),
            SocialName: $(`.social_name-${id}`).val(),
            SocialUrl: $(`.social_url-${id}`).val(),
        };
        apiUpdateSocial(request);
    }
    function apiUpdateSocial(request) {
        $.ajax({
            url: '/api/ManageConfigurationsAPI/UpdateSocial',
            data: JSON.stringify(request),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            success: function (data) {
                alert(data.message);
            },
            error: function (data) {
                console.log(data);
                alert(data.responseJSON.message);
            }
        });
    }


    function updateAddress() {
        var request = {
            Id: @Model.config.Id,
            Address: $('.config-address').val(),
            AddressUrl: $('.config-addressurl').val()
        }
        apiUpdateAddress(request)
    }
    function apiUpdateAddress(request) {
        $.ajax({
            url: '/api/ManageConfigurationsAPI/UpdateAddress',
            data: JSON.stringify(request),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            success: function (data) {
                alert(data.message);
            },
            error: function (data) {
                console.log(data);
                alert(data.responseJSON.message);
            }
        });
    }

    function updateTime() {
        var request = {
            Id: @Model.config.Id,
            StartTime: $('.config-starttime').val(),
            EndTime: $('.config-endtime').val()
        };
        apiUpdateTime(request);
    }
    function apiUpdateTime(request) {
        $.ajax({
            url: '/api/ManageConfigurationsAPI/UpdateTime',
            data: JSON.stringify(request),
            dataType: 'json',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            success: function (data) {
                alert(data.message);
            },
            error: function (data) {
                console.log(data);
                alert(data.responseJSON.message);
            }
        });
    }
</script>